# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageProcessUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(943, 623)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        Form.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 271, 208))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnReadFile = QtWidgets.QPushButton(self.layoutWidget)
        self.btnReadFile.setObjectName("btnReadFile")
        self.verticalLayout.addWidget(self.btnReadFile)
        self.btnShowOriginalFile = QtWidgets.QPushButton(self.layoutWidget)
        self.btnShowOriginalFile.setObjectName("btnShowOriginalFile")
        self.verticalLayout.addWidget(self.btnShowOriginalFile)
        self.btnSave = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        # self.gridLayoutWidget = QtWidgets.QWidget(Form)
        # self.gridLayoutWidget.setGeometry(QtCore.QRect(470, 100, 411, 361))
        # self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        # self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        # self.gridLayout.setContentsMargins(0, 0, 0, 0)
        # self.gridLayout.setObjectName("gridLayout")
        # self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        # self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(3)
        # self.tableWidget.setRowCount(0)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(2, item)
        # self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        # self.label = QtWidgets.QLabel(Form)
        # self.label.setGeometry(QtCore.QRect(470, 70, 131, 16))
        # self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnReadFile.setText(_translate("Form", "视频读入"))
        self.btnShowOriginalFile.setText(_translate("Form", "视频分割"))
        self.btnSave.setText(_translate("Form", "保存结果"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("Form", "视频名称"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("Form", "类别ID"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("Form", "类别名称"))
        # self.label.setText(_translate("Form", "分类结果"))
